import { useState, useEffect } from "react";
// Import the generated index file.
// It is generated by vite.config.ts on start.
import indexData from "../data-index.json";

import type { DailyReportData, WeeklyReportData } from "../types/data";

export function useIndex() {
  return { data: indexData, loading: false, error: null };
}

export function useDailyData(date: string) {
  const [data, setData] = useState<DailyReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        let targetDate = date;

        // Handle "latest" alias
        if (date === "latest") {
          if (!indexData.latest.daily) {
            throw new Error("No daily reports available");
          }
          targetDate = indexData.latest.daily;
        }

        // Fetch from public/data
        const response = await fetch(`/data/daily/${targetDate}.json`);
        if (!response.ok) {
          throw new Error("Report not found");
        }
        const jsonData = await response.json();
        setData(jsonData);
        setError(null);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load data");
        setData(null);
      } finally {
        setLoading(false);
      }
    }

    if (date) {
      fetchData();
    }
  }, [date]);

  return { data, loading, error };
}

export function useWeeklyData(week: string) {
  const [data, setData] = useState<WeeklyReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        let targetWeek = week;

        // Handle "latest" alias for weekly
        if (week === "latest") {
          if (!indexData.latest.weekly) {
            throw new Error("No weekly reports available");
          }
          targetWeek = indexData.latest.weekly;
        }

        const response = await fetch(`/data/weekly/${targetWeek}.json`);
        if (!response.ok) {
          throw new Error("Report not found");
        }
        const jsonData = await response.json();
        setData(jsonData);
        setError(null);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load data");
        setData(null);
      } finally {
        setLoading(false);
      }
    }

    if (week) {
      fetchData();
    }
  }, [week]);

  return { data, loading, error };
}
