import React from 'react';

export interface ReportFooterProps {
  message?: string;
}

/**
 * ReportFooter 组件 - 报告页面底部
 */
export const ReportFooter: React.FC<ReportFooterProps> = ({ 
  message = 'Generated by Obsidian Community Report System' 
}) => (
  <div className="mt-16 text-center text-slate-400 dark:text-slate-500 text-sm italic">
    {message}
  </div>
);
